# Site settings
title: start.ffhh
description:      "Frei von Registrierung, Erfassung von persönlichen Informationen oder zeitlicher Limitierung. Freifunk Hamburg ist ein Netzwerk, an dem jeder teilnehmen kann."
baseurl: ""
organisation:     Freifunk Hamburg
twitter_username: FreifunkHH
github_username:  freifunkhamburg/start-ffhh
about_page:       https://hamburg.freifunk.net/

# Build settings
markdown: kramdown
permalink: pretty
