# Site settings
title: start.ffef
description:      "Frei von Registrierung, Erfassung von persönlichen Informationen oder zeitlicher Limitierung. Freifunk Erfurt ist ein Netz, an dem jeder teilnehmen kann."
baseurl: ""
organisation:     Freifunk Erfurt
twitter_username: FreifunkErfurt
github_username:  freifunkerfurt/start-ffef
about_page:       https://erfurt.freifunk.net/

# Build settings
markdown: kramdown
permalink: pretty
