# .ffhh:
# network: intern
# .com:
# network: public
#
# Pick your icon from here:
# https://fortawesome.github.io/Font-Awesome/icons/
# the fa- is added automatically
#
#- title:    Blogs
#  text:     Worpress im Freifunk-Netz
#  icon:     quote-right
#  url:      http://wp.ffhh/
#  network:  intern
#- title:    Radio
#  text:     Live Stream von freier Musik
#  icon:     file-audio-o
#  url:      http://radio.ffhh/
#  network:  intern
- title:    Wiki
  text:     Unsere Wissenssammlung im Wiki des Technikkultur-Vereins
  icon:     group
  url:      https://www.technikkultur-erfurt.de/freifunk:start
  network:  public
- title:    Verbindung
  text:     Zeigt Informationen über den Router, mit dem du gerade verbunden bist
  icon:     wifi
  url:      http://knoten.ffef/
  network:  intern
- title:    Bilder-Dump
  text:     Bilder schnell und unkompliziert teilen
  icon:     picture-o
  url:      http://10.99.254.1/bilder
  network:  intern
- title:    Chat
  text:     Peer-to-Peer Text, Audio und Video Chats im Browser mit WebRTC
  icon:     comments
  url:      http://chat.ffef
  network:  intern
- title:    FritzB31Server
  text:     Fileserver von SE515
  icon:     file
  url:      http://fritzb31server.ffef
  network:  intern
- title:    Dump1090 (Stephan)
  text:     SDR-Flugradar mit dump1090 auf dem RaspberryPi von Stephan
  icon:     plane
  url:      http://bastelpi.ffef:8080/
  network:  intern
